### ISSUE TITLE
Submit a tutorial based on this to the Apigility documentation

### ISSUE THREAD

**Issue by weierophinney** [cloud-solutions/ApigilityXml#2]
Hey, @markushausammann -- would you be interested in submitting a tutorial to zfcampus/apigility-documentation showing how to do this? What you've done is exactly what we envisioned for allowing alternate serializations, and I think not only the code, but a "how to" guide would be fantastic for those diving deep into Apigility.

**Comment by markushausammann** [comment]
I just can't find time for this. So many things on my plate and I'm already far away again from this topic. Sorry for that but I need to cut a few things and make my todo list feel less overwhelming.
